package org.chorus_oss.protocol.core

import org.chorus_oss.protocol.packets.*

object PacketRegistry {
    private val registry = mutableMapOf<Int, PacketCodec<*>>()

    internal fun register(codec: PacketCodec<*>) {
        registry[codec.id] = codec
    }

    internal fun register(codecs: Iterable<PacketCodec<*>>) = codecs.forEach(::register)

    internal operator fun plusAssign(codec: PacketCodec<*>) = codec.let(::register)

    internal operator fun plusAssign(codecs: Iterable<PacketCodec<*>>) = codecs.let(::register)

    internal operator fun plus(codec: PacketCodec<*>) = codec.let(::register)

    internal operator fun plus(codecs: Iterable<PacketCodec<*>>) = codecs.let(::register)

    operator fun get(id: Int): PacketCodec<*>? = registry[id]

    @Suppress("UNCHECKED_CAST")
    operator fun <T : Packet> get(packet: T): PacketCodec<T>? = registry[packet.id] as? PacketCodec<T>?

    init {
        this += listOf(
            ActorEventPacket,
            ActorPickRequestPacket,
            AddActorPacket,
            AddBehaviorTreePacket,
            AddItemActorPacket,
            AddPaintingPacket,
            AddPlayerPacket,
            AddVolumeActorPacket,
            AgentActionEventPacket,
            AgentAnimationPacket,
            AnimateEntityPacket,
            AnimatePacket,
            AnvilDamagePacket,
            AutomationClientConnectPacket,
            AvailableActorIdentifiersPacket,
            AvailableCommandsPacket,
            AwardAchievementPacket,
            BiomeDefinitionListPacket,
            BlockActorDataPacket,
            BlockEventPacket,
            BlockPickRequestPacket,
            BookEditPacket,
            BossEventPacket,
            CameraAimAssistPacket,
            CameraAimAssistPresetsPacket,
            CameraInstructionPacket,
            CameraPacket,
            CameraPresetsPacket,
            CameraShakePacket,
            ChangeDimensionPacket,
            ChangeMobPropertyPacket,
            ChunkRadiusUpdatedPacket,
            ClientboundCloseFormPacket,
            ClientboundControlSchemeSetPacket,
            ClientboundDebugRendererPacket,
            ClientboundMapItemDataPacket,
            ClientCacheBlobStatusPacket,
            ClientCacheMissResponsePacket,
            ClientCacheStatusPacket,
            ClientCameraAimAssistPacket,
            ClientMovementPredictionSyncPacket,
            ClientToServerHandshakePacket,
            CodeBuilderPacket,
            CodeBuilderSourcePacket,
            CommandBlockUpdatePacket,
            CommandOutputPacket,
            CommandRequestPacket,
            CompletedUsingItemPacket,
            ContainerClosePacket,
            ContainerOpenPacket,
            ContainerRegistryCleanupPacket,
            ContainerSetDataPacket,
            CorrectPlayerMovePredictionPacket,
            CraftingDataPacket,
            CreatePhotoPacket,
            CreativeContentPacket,
            CurrentStructureFeaturePacket,
            DeathInfoPacket,
            DebugInfoPacket,
            DimensionDataPacket,
            DisconnectPacket,
            EditorNetworkPacket,
            EducationSettingsPacket,
            EduUriResourcePacket,
            EmoteListPacket,
            EmotePacket,
            FeatureRegistryPacket,
            GameRulesChangedPacket,
            GameTestRequestPacket,
            GameTestResultsPacket,
            GUIDataPickItemPacket,
            HurtArmorPacket,
            InteractPacket,
            InventoryContentPacket,
            InventorySlotPacket,
            InventoryTransactionPacket,
            ItemRegistryPacket,
            ItemStackRequestPacket,
            ItemStackResponsePacket,
            JigsawStructureDataPacket,
            LabTablePacket,
            LecternUpdatePacket,
            LessonProgressPacket,
            LevelChunkPacket,
            LevelEventGenericPacket,
            LevelEventPacket,
            LevelSoundEventPacket,
            LoginPacket,
            MapCreateLockedCopyPacket,
            MapInfoRequestPacket,
            MobArmorEquipmentPacket,
            MobEffectPacket,
            MobEquipmentPacket,
            ModalFormRequestPacket,
            ModalFormResponsePacket,
            MotionPredictionHintsPacket,
            MoveActorAbsolutePacket,
            MoveActorDeltaPacket,
            MovementEffectPacket,
            MovePlayerPacket,
            MultiplayerSettingsPacket,
            NetworkChunkPublisherUpdatePacket,
            NetworkSettingsPacket,
            NPCDialoguePacket,
            NPCRequestPacket,
            OnScreenTextureAnimationPacket,
            OpenSignPacket,
            PacketViolationWarningPacket,
            PhotoTransferPacket,
            PlayerActionPacket,
            PlayerArmorDamagePacket,
            PlayerAuthInputPacket,
            PlayerEnchantOptionsPacket,
            PlayerFogPacket,
            PlayerHotbarPacket,
            PlayerListPacket,
            PlayerLocationPacket,
            PlayerSkinPacket,
            PlayerStartItemCoolDownPacket,
            PlayerToggleCrafterSlotRequestPacket,
            PlayerUpdateEntityOverridesPacket,
            PlayerVideoCapturePacket,
            PlaySoundPacket,
            PlayStatusPacket,
            PositionTrackingDBClientRequestPacket,
            PositionTrackingDBServerBroadcastPacket,
            PurchaseReceiptPacket,
            RefreshEntitlementsPacket,
            RemoveActorPacket,
            RemoveObjectivePacket,
            RemoveVolumeEntityPacket,
            RequestAbilityPacket,
            RequestChunkRadiusPacket,
            RequestNetworkSettingsPacket,
            RequestPermissionsPacket,
            ResourcePackChunkDataPacket,
            ResourcePackChunkRequestPacket,
            ResourcePackClientResponsePacket,
            ResourcePackDataInfoPacket,
            ResourcePacksInfoPacket,
            ResourcePackStackPacket,
            RespawnPacket,
            ScriptMessagePacket,
            ServerboundDiagnosticsPacket,
            ServerboundLoadingScreenPacket,
            ServerPostMovePositionPacket,
            ServerScriptDebugDrawerPacket,
            ServerSettingsRequestPacket,
            ServerSettingsResponsePacket,
            ServerStatsPacket,
            ServerToClientHandshakePacket,
            SetActorDataPacket,
            SetActorLinkPacket,
            SetActorMotionPacket,
            SetCommandsEnabledPacket,
            SetDefaultGameTypePacket,
            SetDifficultyPacket,
            SetDisplayObjectivePacket,
            SetHealthPacket,
            SetHudPacket,
            SetLastHurtByPacket,
            SetLocalPlayerAsInitializedPacket,
            SetPlayerGameTypePacket,
            SetPlayerInventoryOptionsPacket,
            SetScoreboardIdentityPacket,
            SetScorePacket,
            SetSpawnPositionPacket,
            SetTimePacket,
            SettingsCommandPacket,
            SetTitlePacket,
            ShowCreditsPacket,
            ShowProfilePacket,
            ShowStoreOfferPacket,
            SimpleEventPacket,
            SimulationTypePacket,
            SpawnParticleEffectPacket,
            StartGamePacket,
            StopSoundPacket,
            StructureBlockUpdatePacket,
            StructureTemplateDataExportRequestPacket,
            StructureTemplateDataExportResponsePacket,
            SubChunkPacket,
            SubChunkRequestPacket,
            SubClientLoginPacket,
            SyncActorPropertyPacket,
            TakeItemEntityPacket,
            TextPacket,
            TickingAreasLoadStatusPacket,
            ToastRequestPacket,
            TransferPacket,
            TrimDataPacket,
            UnlockedRecipesPacket,
            UpdateAbilitiesPacket,
            UpdateAdventureSettingsPacket,
            UpdateAttributesPacket,
            UpdateBlockPacket,
            UpdateBlockSyncedPacket,
            UpdateClientInputLocksPacket,
            UpdateClientOptionsPacket,
            UpdateEquipmentPacket,
            UpdatePlayerGameTypePacket,
            UpdateSoftEnumPacket,
            UpdateSubChunkBlocksPacket,
            UpdateTradePacket,
        )
    }
}