package org.chorus_oss.protocol.types.actor_data

import org.chorus_oss.nbt.tags.CompoundTag
import org.chorus_oss.protocol.types.IVector3
import org.chorus_oss.protocol.types.Vector3f
import kotlin.reflect.KClass

sealed class ActorDataType<T : Any>(
    val key: ActorDataKey,
    val type: KClass<T>
) {
    data object Flags : ActorDataType<Long>(ActorDataKey.Flags, Long::class)
    data object StructuralIntegrity : ActorDataType<Int>(ActorDataKey.StructuralIntegrity, Int::class)
    data object Variant : ActorDataType<Int>(ActorDataKey.Variant, Int::class)
    data object ColorIndex : ActorDataType<Byte>(ActorDataKey.ColorIndex, Byte::class)
    data object Name : ActorDataType<String>(ActorDataKey.Name, String::class)
    data object Owner : ActorDataType<Long>(ActorDataKey.Owner, Long::class)
    data object Target : ActorDataType<Long>(ActorDataKey.Target, Long::class)
    data object AirSupply : ActorDataType<Short>(ActorDataKey.AirSupply, Short::class)
    data object EffectColor : ActorDataType<Int>(ActorDataKey.EffectColor, Int::class)
    data object EffectAmbience : ActorDataType<Byte>(ActorDataKey.EffectAmbience, Byte::class)
    data object JumpDuration : ActorDataType<Byte>(ActorDataKey.JumpDuration, Byte::class)
    data object Hurt : ActorDataType<Int>(ActorDataKey.Hurt, Int::class)
    data object HurtDirection : ActorDataType<Int>(ActorDataKey.HurtDirection, Int::class)
    data object RowTimeLeft : ActorDataType<Float>(ActorDataKey.RowTimeLeft, Float::class)
    data object RowTimeRight : ActorDataType<Float>(ActorDataKey.RowTimeRight, Float::class)
    data object Value : ActorDataType<Int>(ActorDataKey.Value, Int::class)
    data object DisplayTileRuntimeID : ActorDataType<Int>(ActorDataKey.DisplayTileRuntimeID, Int::class)
    data object DisplayOffset : ActorDataType<Int>(ActorDataKey.DisplayOffset, Int::class)
    data object CustomDisplay : ActorDataType<Byte>(ActorDataKey.CustomDisplay, Byte::class)
    data object Swell : ActorDataType<Byte>(ActorDataKey.Swell, Byte::class)
    data object OldSwell : ActorDataType<Int>(ActorDataKey.OldSwell, Int::class)
    data object SwellDirection : ActorDataType<Int>(ActorDataKey.SwellDirection, Int::class)
    data object ChargeAmount : ActorDataType<Byte>(ActorDataKey.ChargeAmount, Byte::class)
    data object CarryBlockRuntimeID : ActorDataType<Int>(ActorDataKey.CarryBlockRuntimeID, Int::class)
    data object ClientEvent : ActorDataType<Byte>(ActorDataKey.ClientEvent, Byte::class)
    data object UsingItem : ActorDataType<Byte>(ActorDataKey.UsingItem, Byte::class)
    data object PlayerFlags : ActorDataType<Byte>(ActorDataKey.PlayerFlags, Byte::class)
    data object PlayerIndex : ActorDataType<Int>(ActorDataKey.PlayerIndex, Int::class)
    data object BedPosition : ActorDataType<IVector3>(ActorDataKey.BedPosition, IVector3::class)
    data object PowerX : ActorDataType<Float>(ActorDataKey.PowerX, Float::class)
    data object PowerY : ActorDataType<Float>(ActorDataKey.PowerY, Float::class)
    data object PowerZ : ActorDataType<Float>(ActorDataKey.PowerZ, Float::class)
    data object AuxPower : ActorDataType<Byte>(ActorDataKey.AuxPower, Byte::class)
    data object FishX : ActorDataType<Float>(ActorDataKey.FishX, Float::class)
    data object FishZ : ActorDataType<Float>(ActorDataKey.FishZ, Float::class)
    data object FishAngle : ActorDataType<Float>(ActorDataKey.FishAngle, Float::class)
    data object AuxValueData : ActorDataType<Short>(ActorDataKey.AuxValueData, Short::class)
    data object LeashHolder : ActorDataType<Long>(ActorDataKey.LeashHolder, Long::class)
    data object Scale : ActorDataType<Float>(ActorDataKey.Scale, Float::class)
    data object HasNPC : ActorDataType<Byte>(ActorDataKey.HasNPC, Byte::class)
    data object NPCData : ActorDataType<String>(ActorDataKey.NPCData, String::class)
    data object Actions : ActorDataType<String>(ActorDataKey.Actions, String::class)
    data object AirSupplyMax : ActorDataType<Short>(ActorDataKey.AirSupplyMax, Short::class)
    data object MarkVariant : ActorDataType<Int>(ActorDataKey.MarkVariant, Int::class)
    data object ContainerType : ActorDataType<Byte>(ActorDataKey.ContainerType, Byte::class)
    data object ContainerSize : ActorDataType<Int>(ActorDataKey.ContainerSize, Int::class)
    data object ContainerStrengthModifier : ActorDataType<Int>(ActorDataKey.ContainerStrengthModifier, Int::class)
    data object BlockTarget : ActorDataType<IVector3>(ActorDataKey.BlockTarget, IVector3::class)
    data object Inventory : ActorDataType<Int>(ActorDataKey.Inventory, Int::class)
    data object TargetA : ActorDataType<Long>(ActorDataKey.TargetA, Long::class)
    data object TargetB : ActorDataType<Long>(ActorDataKey.TargetB, Long::class)
    data object TargetC : ActorDataType<Long>(ActorDataKey.TargetC, Long::class)
    data object AerialAttack : ActorDataType<Short>(ActorDataKey.AerialAttack, Short::class)
    data object Width : ActorDataType<Float>(ActorDataKey.Width, Float::class)
    data object Height : ActorDataType<Float>(ActorDataKey.Height, Float::class)
    data object FuseTime : ActorDataType<Int>(ActorDataKey.FuseTime, Int::class)
    data object SeatOffset : ActorDataType<Vector3f>(ActorDataKey.SeatOffset, Vector3f::class)
    data object SeatLockPassengerRotation : ActorDataType<Byte>(ActorDataKey.SeatLockPassengerRotation, Byte::class)
    data object SeatLockPassengerRotationDegrees :
        ActorDataType<Float>(ActorDataKey.SeatLockPassengerRotationDegrees, Float::class)

    data object SeatRotationOffset : ActorDataType<Byte>(ActorDataKey.SeatRotationOffset, Byte::class)
    data object SeatRotationOffsetDegrees : ActorDataType<Float>(ActorDataKey.SeatRotationOffsetDegrees, Float::class)
    data object DataRadius : ActorDataType<Float>(ActorDataKey.DataRadius, Float::class)
    data object DataWaiting : ActorDataType<Int>(ActorDataKey.DataWaiting, Int::class)
    data object DataParticle : ActorDataType<Int>(ActorDataKey.DataParticle, Int::class)
    data object PeekID : ActorDataType<Int>(ActorDataKey.PeekID, Int::class)
    data object AttachFace : ActorDataType<Int>(ActorDataKey.AttachFace, Int::class)
    data object Attached : ActorDataType<Byte>(ActorDataKey.Attached, Byte::class)
    data object AttachedPosition : ActorDataType<IVector3>(ActorDataKey.AttachedPosition, IVector3::class)
    data object TradeTarget : ActorDataType<Long>(ActorDataKey.TradeTarget, Long::class)
    data object Career : ActorDataType<Int>(ActorDataKey.Career, Int::class)
    data object HasCommandBlock : ActorDataType<Byte>(ActorDataKey.HasCommandBlock, Byte::class)
    data object CommandName : ActorDataType<String>(ActorDataKey.CommandName, String::class)
    data object LastCommandOutput : ActorDataType<String>(ActorDataKey.LastCommandOutput, String::class)
    data object TrackCommandOutput : ActorDataType<Byte>(ActorDataKey.TrackCommandOutput, Byte::class)
    data object ControllingSeatIndex : ActorDataType<Byte>(ActorDataKey.ControllingSeatIndex, Byte::class)
    data object Strength : ActorDataType<Int>(ActorDataKey.Strength, Int::class)
    data object StrengthMax : ActorDataType<Int>(ActorDataKey.StrengthMax, Int::class)
    data object DataSpellCastingColor : ActorDataType<Int>(ActorDataKey.DataSpellCastingColor, Int::class)
    data object DataLifetimeTicks : ActorDataType<Int>(ActorDataKey.DataLifetimeTicks, Int::class)
    data object PoseIndex : ActorDataType<Int>(ActorDataKey.PoseIndex, Int::class)
    data object DataTickOffset : ActorDataType<Int>(ActorDataKey.DataTickOffset, Int::class)
    data object AlwaysShowNameTag : ActorDataType<Byte>(ActorDataKey.AlwaysShowNameTag, Byte::class)
    data object ColorTwoIndex : ActorDataType<Byte>(ActorDataKey.ColorTwoIndex, Byte::class)
    data object NameAuthor : ActorDataType<String>(ActorDataKey.NameAuthor, String::class)
    data object Score : ActorDataType<String>(ActorDataKey.Score, String::class)
    data object BalloonAnchor : ActorDataType<Long>(ActorDataKey.BalloonAnchor, Long::class)
    data object PuffedState : ActorDataType<Byte>(ActorDataKey.PuffedState, Byte::class)
    data object BubbleTime : ActorDataType<Int>(ActorDataKey.BubbleTime, Int::class)
    data object Agent : ActorDataType<Long>(ActorDataKey.Agent, Long::class)
    data object SittingAmount : ActorDataType<Float>(ActorDataKey.SittingAmount, Float::class)
    data object SittingAmountPrevious : ActorDataType<Float>(ActorDataKey.SittingAmountPrevious, Float::class)
    data object EatingCounter : ActorDataType<Int>(ActorDataKey.EatingCounter, Int::class)
    data object FlagsTwo : ActorDataType<Long>(ActorDataKey.FlagsTwo, Long::class)
    data object LayingAmount : ActorDataType<Float>(ActorDataKey.LayingAmount, Float::class)
    data object LayingAmountPrevious : ActorDataType<Float>(ActorDataKey.LayingAmountPrevious, Float::class)
    data object DataDuration : ActorDataType<Int>(ActorDataKey.DataDuration, Int::class)
    data object DataSpawnTime : ActorDataType<Int>(ActorDataKey.DataSpawnTime, Int::class)
    data object DataChangeRate : ActorDataType<Float>(ActorDataKey.DataChangeRate, Float::class)
    data object DataChangeOnPickup : ActorDataType<Float>(ActorDataKey.DataChangeOnPickup, Float::class)
    data object DataPickupCount : ActorDataType<Int>(ActorDataKey.DataPickupCount, Int::class)
    data object InteractText : ActorDataType<String>(ActorDataKey.InteractText, String::class)
    data object TradeTier : ActorDataType<Int>(ActorDataKey.TradeTier, Int::class)
    data object MaxTradeTier : ActorDataType<Int>(ActorDataKey.MaxTradeTier, Int::class)
    data object TradeExperience : ActorDataType<Int>(ActorDataKey.TradeExperience, Int::class)
    data object SkinID : ActorDataType<Int>(ActorDataKey.SkinID, Int::class)
    data object SpawningFrames : ActorDataType<Int>(ActorDataKey.SpawningFrames, Int::class)
    data object CommandBlockTickDelay : ActorDataType<Int>(ActorDataKey.CommandBlockTickDelay, Int::class)
    data object CommandBlockExecuteOnFirstTick :
        ActorDataType<Byte>(ActorDataKey.CommandBlockExecuteOnFirstTick, Byte::class)

    data object AmbientSoundInterval : ActorDataType<Float>(ActorDataKey.AmbientSoundInterval, Float::class)
    data object AmbientSoundIntervalRange : ActorDataType<Float>(ActorDataKey.AmbientSoundIntervalRange, Float::class)
    data object AmbientSoundEventName : ActorDataType<String>(ActorDataKey.AmbientSoundEventName, String::class)
    data object FallDamageMultiplier : ActorDataType<Float>(ActorDataKey.FallDamageMultiplier, Float::class)
    data object NameRawText : ActorDataType<String>(ActorDataKey.NameRawText, String::class)
    data object CanRideTarget : ActorDataType<Byte>(ActorDataKey.CanRideTarget, Byte::class)
    data object LowTierCuredTradeDiscount : ActorDataType<Int>(ActorDataKey.LowTierCuredTradeDiscount, Int::class)
    data object HighTierCuredTradeDiscount : ActorDataType<Int>(ActorDataKey.HighTierCuredTradeDiscount, Int::class)
    data object NearbyCuredTradeDiscount : ActorDataType<Int>(ActorDataKey.NearbyCuredTradeDiscount, Int::class)
    data object NearbyCuredDiscountTimeStamp : ActorDataType<Int>(ActorDataKey.NearbyCuredDiscountTimeStamp, Int::class)
    data object Hitbox : ActorDataType<CompoundTag>(ActorDataKey.HitBox, CompoundTag::class)
    data object IsBuoyant : ActorDataType<Byte>(ActorDataKey.IsBuoyant, Byte::class)
    data object FreezingEffectStrength : ActorDataType<Float>(ActorDataKey.FreezingEffectStrength, Float::class)
    data object BuoyancyData : ActorDataType<String>(ActorDataKey.BuoyancyData, String::class)
    data object GoatHornCount : ActorDataType<Int>(ActorDataKey.GoatHornCount, Int::class)
    data object BaseRuntimeID : ActorDataType<String>(ActorDataKey.BaseRuntimeID, String::class)
    data object MovementSoundDistanceOffset :
        ActorDataType<Float>(ActorDataKey.MovementSoundDistanceOffset, Float::class)

    data object HeartbeatIntervalTicks : ActorDataType<Int>(ActorDataKey.HeartbeatIntervalTicks, Int::class)
    data object HeartbeatSoundEvent : ActorDataType<Int>(ActorDataKey.HeartbeatSoundEvent, Int::class)
    data object PlayerLastDeathPosition : ActorDataType<IVector3>(ActorDataKey.PlayerLastDeathPosition, IVector3::class)
    data object PlayerLastDeathDimension : ActorDataType<Int>(ActorDataKey.PlayerLastDeathDimension, Int::class)
    data object PlayerHasDied : ActorDataType<Byte>(ActorDataKey.PlayerHasDied, Byte::class)
    data object CollisionBox : ActorDataType<Vector3f>(ActorDataKey.CollisionBox, Vector3f::class)
    data object VisibleMobEffects : ActorDataType<Long>(ActorDataKey.VisibleMobEffects, Long::class)
    data object FilteredName : ActorDataType<String>(ActorDataKey.FilteredName, String::class)
    data object BedEnterPosition : ActorDataType<Vector3f>(ActorDataKey.BedEnterPosition, Vector3f::class)
    data object SeatThirdPersonCameraRadius :
        ActorDataType<Float>(ActorDataKey.SeatThirdPersonCameraRadius, Float::class)

    data object SeatCameraRelaxDistanceSmoothing :
        ActorDataType<Float>(ActorDataKey.SeatCameraRelaxDistanceSmoothing, Float::class)
}
