package org.chorus_oss.protocol.types.actor_data

import kotlinx.io.Buffer
import org.chorus_oss.protocol.core.ProtoCodec
import org.chorus_oss.protocol.core.ProtoVAR
import org.chorus_oss.protocol.core.types.UInt

enum class ActorDataKey {
    Flags,
    StructuralIntegrity,
    Variant,
    ColorIndex,
    Name,
    Owner,
    Target,
    AirSupply,
    EffectColor,
    EffectAmbience,
    JumpDuration,
    Hurt,
    HurtDirection,
    RowTimeLeft,
    RowTimeRight,
    Value,
    DisplayTileRuntimeID,
    DisplayOffset,
    CustomDisplay,
    Swell,
    OldSwell,
    SwellDirection,
    ChargeAmount,
    CarryBlockRuntimeID,
    ClientEvent,
    UsingItem,
    PlayerFlags,
    PlayerIndex,
    BedPosition,
    PowerX,
    PowerY,
    PowerZ,
    AuxPower,
    FishX,
    FishZ,
    FishAngle,
    AuxValueData,
    LeashHolder,
    Scale,
    HasNPC,
    NPCData,
    Actions,
    AirSupplyMax,
    MarkVariant,
    ContainerType,
    ContainerSize,
    ContainerStrengthModifier,
    BlockTarget,
    Inventory,
    TargetA,
    TargetB,
    TargetC,
    AerialAttack,
    Width,
    Height,
    FuseTime,
    SeatOffset,
    SeatLockPassengerRotation,
    SeatLockPassengerRotationDegrees,
    SeatRotationOffset,
    SeatRotationOffsetDegrees,
    DataRadius,
    DataWaiting,
    DataParticle,
    PeekID,
    AttachFace,
    Attached,
    AttachedPosition,
    TradeTarget,
    Career,
    HasCommandBlock,
    CommandName,
    LastCommandOutput,
    TrackCommandOutput,
    ControllingSeatIndex,
    Strength,
    StrengthMax,
    DataSpellCastingColor,
    DataLifetimeTicks,
    PoseIndex,
    DataTickOffset,
    AlwaysShowNameTag,
    ColorTwoIndex,
    NameAuthor,
    Score,
    BalloonAnchor,
    PuffedState,
    BubbleTime,
    Agent,
    SittingAmount,
    SittingAmountPrevious,
    EatingCounter,
    FlagsTwo,
    LayingAmount,
    LayingAmountPrevious,
    DataDuration,
    DataSpawnTime,
    DataChangeRate,
    DataChangeOnPickup,
    DataPickupCount,
    InteractText,
    TradeTier,
    MaxTradeTier,
    TradeExperience,
    SkinID,
    SpawningFrames,
    CommandBlockTickDelay,
    CommandBlockExecuteOnFirstTick,
    AmbientSoundInterval,
    AmbientSoundIntervalRange,
    AmbientSoundEventName,
    FallDamageMultiplier,
    NameRawText,
    CanRideTarget,
    LowTierCuredTradeDiscount,
    HighTierCuredTradeDiscount,
    NearbyCuredTradeDiscount,
    NearbyCuredDiscountTimeStamp,
    HitBox,
    IsBuoyant,
    FreezingEffectStrength,
    BuoyancyData,
    GoatHornCount,
    BaseRuntimeID,
    MovementSoundDistanceOffset,
    HeartbeatIntervalTicks,
    HeartbeatSoundEvent,
    PlayerLastDeathPosition,
    PlayerLastDeathDimension,
    PlayerHasDied,
    CollisionBox,
    VisibleMobEffects,
    FilteredName,
    BedEnterPosition,
    SeatThirdPersonCameraRadius,
    SeatCameraRelaxDistanceSmoothing;

    companion object : ProtoCodec<ActorDataKey> {
        override fun serialize(value: ActorDataKey, stream: Buffer) {
            ProtoVAR.UInt.serialize(value.ordinal.toUInt(), stream)
        }

        override fun deserialize(stream: Buffer): ActorDataKey {
            return entries[ProtoVAR.UInt.deserialize(stream).toInt()]
        }

    }
}